### ISSUE TITLE
Wrong hostname & CODER_INNER_HOSTNAME ignored

### ISSUE THREAD

**Issue by szab100** [coder/envbox#43]
Using the [template from this repo](https://github.com/coder/envbox/blob/main/template.tf) (same image tags used), the inner container has a fixed hostname of `workspacecvm`, which does not match with its `/etc/hosts` entry:

`172.19.0.2      workspace_cvm`

this causes the following error when running various commands:
```
coder@workspacecvm:/workspace$ sudo su
sudo: unable to resolve host workspacecvm: Name or service not known
root@workspacecvm:/workspace# 
```

I tried setting the `CODER_INNER_HOSTNAME` env var, but it does not seem to update the inner container's hostname at all.

**Comment by szab100** [comment]
The hostname issue described above might be due to it is having an underscore, which is not valid: https://kb.iu.edu/d/afqs

**Comment by sreya** [comment]
Hey @szab100 sorry for missing this. Unfortunately that template is a relic from when I was initially setting up and developing the repo (if you couldn't tell :slightly_smiling_face: ). You can find the maintained template [here](https://github.com/coder/coder/tree/main/examples/templates/envbox).  

For what it's worth I validated that the `CODER_INNER_HOSTNAME` is being set correctly. Feel free to reopen or create a new issue if you're still encountering problems.

**Comment by szab100** [comment]
Hey @sreya, yeah thanks a lot, it sure felt like a development phase template (with image tags like "testttt" / fixed commit hash), its just that [the feature's documentation](https://coder.com/docs/v2/latest/templates/docker-in-workspaces#envbox) was pointing to this file here.. But I see it is now updated as well, thanks!

**Comment by szab100** [comment]
@sreya Sorry, one more question: I see the enterprise-base inner image is still referenced by a fixed commit hash tag.. is there a particular reason why it is "pinned" or should all the `enterprise-*:latest` images work ?!

**Comment by sreya** [comment]
> I see the enterprise-base inner image is still referenced by a fixed commit hash tag.. is there a particular reason why it is "pinned" or should all the enterprise-*:latest images work ?!

No I believe you should be able to use the `latest` tag without issue, I can't remember why it's pinned to commit, I'll update it to just be the tag. In general the inner image can be whatever you like, if you're using envbox with Coder the image will simply need some basic tools like `curl` to bootstrap the workspace.

>  The README.md says “envbox is an image that enables creating non-privileged containers capable of running system-level software” - however, the outer container is privileged.. i’m trying to figure out how much is this different from installing Sysbox on the nodes & run the workspace with runtime-class: sysbox. It seems the key disadvantages of Envbox are slower workspace start times and performance (DinD overhead).. But there are advantages too, like the provided tun & fuse devices (can this be achieved via runtime-class ?).

The experience really shouldn't be all that different and in fact we encourage you to run sysbox directly on the nodes if that's something you wish to maintain. The main advantage of `envbox` is that it packages up and manages running all the sysbox dependencies for you. I'm not sure if you can mount in character devices into an unprivileged pod and expect them to work but it's worth giving it a shot.
