### ISSUE TITLE
Display workspace memory usage on Coder dashboard

### ISSUE THREAD

**Issue by mambon2** [coder/envbox#74]
Currently users using envbox workspaces are not able to monitor their memory usage without having direct access to the k8s cluster.   Please display real time memory usage of the pod/container in the Coder dashboard.

**Comment by matifali** [comment]
Hi @mambon2 
You can display these usage values using the `coder stat` command and utilizing [`metadata`](https://registry.terraform.io/providers/coder/coder/latest/docs/resources/agent#metadata) property if the `coder_agent`. 

A full example can be seen here. 
https://github.com/coder/coder/blob/2cfadad023cb7f4f85710cff0b21ac46bdb5a845/examples/templates/docker/main.tf#L59-L73
