### ISSUE TITLE
Investigate agent freezes

### ISSUE THREAD

**Issue by code-asher** [coder/envbox#99]
Just creating this to make sure we keep track of this in case we add back the signal handling.

Reportedly, in 0.5.0 workspaces stop being responsive randomly (IDEs, web terminal, everything), the agent is no longer writing logs, and sending it SIGTERM and SIGINT did nothing.  SIGKILL and restarting the agent fixes the issue until it happens again.

More details, logs, strace, and the template in https://coder.zendesk.com/agent/tickets/3110

**Comment by sreya** [comment]
No longer an issue since reverting the signal handling
